version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: weengz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weengz
      POSTGRES_USER: weengz
      POSTGRES_PASSWORD: weengz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: weengz_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@weengz.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
